name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go tests
        working-directory: ./worker
        run: go test ./... -v

      - name: Build Go app Docker image
        working-directory: ./worker
        run: docker build -t insight-worker:latest .

      - name: Build Express app Docker image
        working-directory: ./api
        run: docker build -t insight-api:latest .
